## Travis CI configuration for the cookiecutter-cpp-app project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-cpp-app>
##
language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - dev

dist: xenial

before_script:
  # Install Cookiecutter. Because this is a C++ project Travis does not create
  # a Python virtualenv, so pip needs to install locally.
  - pyenv local 3.6.7
  - python -m pip install --requirement=requirements.txt --user
  
script:
  - python tests/test_template.py
